hidden_layers:
- 64
- 32
- 32 
- 32
input_bitwidth: 2
hidden_bitwidth: 2
output_bitwidth: 2
input_fanin: 3
hidden_fanin: 3
output_fanin: 3
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 2
checkpoint: null
