batch_size: 128
ensemble_method: averaging
ensemble_size: 2
epochs: 500
gpu: true
hidden_bitwidth: 2
hidden_fanin: 6
hidden_layers:
- 256
- 100
- 100
- 100
input_bitwidth: 2
input_fanin: 6
input_length: 784
learning_rate: 0.003
output_bitwidth: 2
output_fanin: 6
output_length: 10
post_transform_output: true
same_input_scale: true
same_output_scale: true
seed: 8971561
weight_decay: 0
width_n: 16
