# Fixed params
ensemble_method: adaboost
hidden_layers: 
- 128
- 64
- 64
- 64
input_bitwidth: 7
hidden_bitwidth: 5
output_bitwidth: 5
input_fanin: 2
degree: 2 # 4
hidden_fanin: 3
output_fanin: 3
weight_decay: 0
batch_size: 1024
epochs: 500
learning_rate: 0.01
seed: 1234
checkpoint: null

# Params to grid search
grid_search_params:
  ensemble_size:
  # - 1
  # - 2
  # - 4
  # - 8
  # - 16
  - 32