# Fixed params
ensemble_method: averaging
hidden_layers:
- 64
- 32
- 32 
- 32
input_bitwidth: 2
hidden_bitwidth: 2
output_bitwidth: 2
input_fanin: 3
hidden_fanin: 3
output_fanin: 3
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 2
checkpoint: null
quantize_avg: false
same_input_scale: false
input_post_trans_sbs: false

shared_input_quant: true
shared_input_layer: true

post_transform_output: true
same_output_scale: false
same_output_scale_sum: false

uniform_input_connectivity: false
uniform_connectivity: false

# Params to grid search
grid_search_params:
  shared_input_bitwidth: 
  - 6
  # - 8
  ensemble_size:
  # - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  # seed:
  # - 1
