# Fixed params
ensemble_method: averaging
# independent: true
hidden_layers:
- 32
- 64
- 192
- 192
- 16
input_bitwidth: 4
hidden_bitwidth: 3
output_bitwidth: 7
# shared_output_bitwidth: 8 # output bitwidth of ensemble members, if defined
# shared_output_fanin: 1
input_fanin: 3
hidden_fanin: 4
output_fanin: 5
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 1
checkpoint: null
quantize_avg: false
same_input_scale: false
input_post_trans_sbs: false

shared_input_quant: true
shared_input_layer: true
shared_input_bitwidth: 6

shared_output_layer: false
post_transform_output: true
same_output_scale: false
same_output_scale_sum: false

uniform_input_connectivity: false
uniform_connectivity: false

# Params to grid search
grid_search_params:
  ensemble_size:
  - 2
  - 4
  - 8
  - 16
  - 32