batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 2
epochs: 1000
hidden_bitwidth: 1
hidden_fanin: 8
hidden_layers:
- 1024
- 1024
- 128
input_bitwidth: 1
input_dropout: 0.01
input_fanin: 8
learning_rate: 0.001
output_bitwidth: 4
output_fanin: 8
same_input_scale: true
same_output_scale: true
seed: 0
shared_input_layer: false
shared_output_layer: false
weight_decay: 0.001
