batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 8
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 6
hidden_layers:
- 1024
- 1024
- 1024
- 1024
- 1024
- 128
input_bitwidth: 2
input_dropout: 0.1
input_fanin: 6
input_length: 784
learning_rate: 0.001
output_bitwidth: 4
output_fanin: 6
output_length: 10
seed: 12
shared_input_bitwidth: 6
shared_input_layer: false
shared_output_layer: false
weight_decay: 0.001
