batch_size: 1024
degree: 3
ensemble_method: averaging
ensemble_size: 8
epochs: 1000
hidden_bitwidth: 3
hidden_fanin: 3
hidden_layers:
- 128
- 128
- 128
- 64
input_bitwidth: 5
input_dropout: 0.001
input_fanin: 2
input_length: 784
learning_rate: 0.001
output_bitwidth: 3
output_fanin: 3
output_length: 10
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 2
shared_input_bitwidth: 6
shared_input_layer: true
shared_output_bitwidth: 4
shared_output_fanin: 1
shared_output_layer: true
weight_decay: 0
