hidden_layers:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 128
input_bitwidth: 1
hidden_bitwidth: 1
output_bitwidth: 4
input_fanin: 6
hidden_fanin: 6
output_fanin: 6
input_dropout: 0.1
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 18
checkpoint: null