batch_size: 1024
checkpoint: null
degree: 2
ensemble_method: averaging
ensemble_size: 1
epochs: 500
hidden_bitwidth: 5
hidden_fanin: 3
hidden_layers:
- 128
- 64
- 64
- 64
input_bitwidth: 7
input_fanin: 2
learning_rate: 0.01
output_bitwidth: 5
output_fanin: 3
seed: 1234
shared_input_bitwidth: 6
shared_input_layer: true
shared_output_bitwidth: 6
shared_output_fanin: 1
shared_output_layer: true
weight_decay: 0
