activation_bitwidth:
- 2
- 2
- 2
- 6
batch_size: 512
ensemble_hp:
  fixed_sparsity_mask: false
  shared_input_bitwidth: 6
  shared_input_layer: true
  shared_output_bitwidth: 7
  shared_output_fanin: 1
  shared_output_layer: true
ensemble_method: voting
ensemble_size: 1
epochs: 200
hidden_layer:
- 128
- 256
- 128
- 128
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 6
- 5
- 4
- 2
output_bitwidth: 6
seed: 2
warm_restart_freq: 100
wd: 0
