batch_size: 1024
degree: 3
ensemble_method: averaging
ensemble_size: 8
epochs: 1000
gpu: true
hidden_bitwidth: 2
hidden_fanin: 3
hidden_layers:
- 64
input_bitwidth: 2
input_dropout: 0.001
input_fanin: 3
input_length: 16
input_post_trans_sbs: false
input_post_trans_ssb: false
learning_rate: 0.001
output_bitwidth: 2
output_fanin: 3
output_length: 5
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 1
shared_input_bitwidth: 6
shared_input_layer: true
shared_output_bitwidth: 3
shared_output_fanin: 1
shared_output_layer: true
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0
