batch_size: 1024
checkpoint: null
ensemble_method: bagging
ensemble_size: 16
epochs: 1000
hidden_bitwidth: 1
hidden_fanin: 8
hidden_layers:
- 1024
- 1024
- 128
independent: true
input_bitwidth: 1
input_dropout: 0.01
input_fanin: 8
input_length: 784
learning_rate: 0.001
output_bitwidth: 4
output_fanin: 8
output_length: 10
seed: 0
shared_input_bitwidth: 6
shared_input_layer: true
shared_output_bitwidth: 5
shared_output_fanin: 1
shared_output_layer: true
weight_decay: 0.001
