batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 1
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 3
hidden_layers:
- 64
- 32
- 32
- 32
input_bitwidth: 2
input_fanin: 3
input_length: 16
input_post_trans_sbs: false
input_post_trans_ssb: false
learning_rate: 0.001
output_bitwidth: 2
output_fanin: 3
output_length: 5
post_transform_output: true
quantize_avg: false
same_input_scale: false
same_output_scale: false
same_output_scale_sum: false
seed: 1
shared_input_bitwidth: 6
shared_input_layer: true
shared_input_quant: true
shared_output_bitwidth: 4
shared_output_fanin: 1
shared_output_layer: true
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0.001
