batch_size: 256
degree: 2
ensemble_method: averaging
ensemble_size: 8
epochs: 500
gpu: true
hidden_bitwidth: 2
hidden_fanin: 4
hidden_layers:
- 600
- 300
- 300
input_bitwidth: 2
input_dropout: 0.01
input_fanin: 4
input_length: 784
input_post_trans_sbs: false
input_post_trans_ssb: false
learning_rate: 0.003
output_bitwidth: 2
output_fanin: 4
output_length: 10
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 8971561
shared_input_bitwidth: 6
shared_input_layer: false
shared_output_layer: false
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0.001
