batch_size: 1024
checkpoint: null
degree: 2
ensemble_method: averaging
ensemble_size: 4
epochs: 1000
gpu: true
hidden_bitwidth: 3
hidden_fanin: 4
hidden_layers:
- 64
- 32
input_bitwidth: 3
input_fanin: 4
input_length: 16
input_post_trans_sbs: false
input_post_trans_ssb: false
learning_rate: 0.001
output_bitwidth: 3
output_fanin: 4
output_length: 5
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 1697
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0
