batch_size: 1024
checkpoint: null
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 5
hidden_layers:
- 1024
- 1024
- 1024
- 1024
- 1024
- 128
input_bitwidth: 2
input_dropout: 0.1
input_fanin: 5
input_length: 784
learning_rate: 0.001
output_bitwidth: 4
output_fanin: 5
output_length: 10
seed: 20
weight_decay: 0.001
