batch_size: 128
degree: 3
ensemble_method: averaging
ensemble_size: 8
epochs: 500
gpu: true
hidden_bitwidth: 2
hidden_fanin: 6
hidden_layers:
- 256
- 100
- 100
- 100
- 100
input_bitwidth: 2
input_fanin: 6
input_length: 784
input_post_trans_sbs: false
input_post_trans_ssb: false
learning_rate: 0.004
output_bitwidth: 2
output_fanin: 6
output_length: 10
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 984237
shared_input_layer: false
shared_output_layer: false
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0
