# Fixed params
activation_bitwidth:
- 3
- 4
batch_size: 512
epochs: 200
hidden_layer:
- 64
- 128
input_bitwidth: 5
input_fanin: 2
lr: 0.001
neuron_fanin:
- 3
- 3
output_bitwidth: 4
warm_restart_freq: 100
wd: 0.0001

# Params to grid search
grid_search_params:
  seed:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  degree:
  - 1
  - 2