ensemble_method: averaging
hidden_layers:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 128
input_bitwidth: 1
hidden_bitwidth: 1
output_bitwidth: 4
shared_output_bitwidth: 5 # output bitwidth of ensemble members, if defined
shared_output_fanin: 1
input_fanin: 8
hidden_fanin: 8
output_fanin: 8
input_dropout: 0.01
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 5
checkpoint: null

shared_input_layer: true
shared_input_bitwidth: 6

shared_output_layer: true

# Params to grid search
grid_search_params:
  ensemble_size:
  - 2
  - 4
  - 8
  - 16
  - 32