# Mnist L 1.1
ensemble_method: averaging
# independent: true
hidden_layers:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 128
input_bitwidth: 2
hidden_bitwidth: 2
output_bitwidth: 4
# shared_output_bitwidth: 5 # output bitwidth of ensemble members, if defined
# shared_output_fanin: 1
input_fanin: 6
hidden_fanin: 6
output_fanin: 6
input_dropout: 0.1
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 12
checkpoint: null

shared_input_layer: false
shared_input_bitwidth: 6

shared_output_layer: false

# Params to grid search
grid_search_params:
  ensemble_size:
  - 2
  - 4
  - 8
  - 16
  - 32