# Fixed params
ensemble_method: averaging
ensemble_size: 8
batch_size: 256
degree: 3
epochs: 500
hidden_bitwidth: 2
hidden_fanin: 4
hidden_layers:
- 600
- 300
- 300
input_bitwidth: 2
shared_output_bitwidth: 3
shared_output_fanin: 1
output_bitwidth: 2
input_dropout: 0.01
input_fanin: 4
input_length: 784
learning_rate: 0.003
output_fanin: 4
output_length: 10
post_transform_output: true
same_input_scale: false
same_output_scale: false
seed: 1
weight_decay: 0.001

shared_input_layer: true
shared_input_bitwidth: 6

shared_output_layer: true


# Params to grid search
grid_search_params:
  ensemble_size:
  - 2
  - 4
  # - 8
  # seed: 
  # - 1
  # - 2
  # - 3