# Fixed params
ensemble_method: adaboost
hidden_layers: 
- 256
- 100
- 100
- 100
- 100
input_bitwidth: 2
hidden_bitwidth: 2
output_bitwidth: 2
input_fanin: 6
degree: 1
hidden_fanin: 6
output_fanin: 6
weight_decay: 0
batch_size: 128
epochs: 500
learning_rate: 0.004
seed: 984237
same_output_scale: false

# Params to grid search
grid_search_params:
  ensemble_size:
  # - 2
  # - 4
  # - 8
  # - 16
  - 32