batch_size: 1024
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 3
hidden_layers:
- 64
input_bitwidth: 2
input_dropout: 0.001
input_fanin: 3
input_length: 784
learning_rate: 0.001
output_bitwidth: 2
output_fanin: 3
output_length: 10
seed: 1
weight_decay: 0
degree: 3