hidden_layers:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 128
input_bitwidth: 3
hidden_bitwidth: 3
output_bitwidth: 4
input_fanin: 3
hidden_fanin: 3
output_fanin: 3
input_dropout: 0.01
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 0
checkpoint: null