batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 2
epochs: 1000
hidden_bitwidth: 3
hidden_fanin: 4
hidden_layers:
- 32
- 64
- 192
- 192
- 16
input_bitwidth: 4
input_fanin: 3
input_post_trans_sbs: false
learning_rate: 0.001
output_bitwidth: 7
output_fanin: 5
post_transform_output: true
quantize_avg: false
same_input_scale: false
same_output_scale: false
same_output_scale_sum: false
seed: 1
shared_input_bitwidth: 6
shared_input_layer: true
shared_input_quant: true
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0.001
