batch_size: 128
width_n: 16
ensemble_method: averaging
ensemble_size: 2
epochs: 500
hidden_bitwidth: 2
hidden_fanin: 6
hidden_layers:
- 128
- 50
- 50
input_bitwidth: 2
input_dropout: 0.001
input_fanin: 6
learning_rate: 0.003
output_bitwidth: 2
output_fanin: 6
shared_input_bitwidth: 6
shared_input_layer: true
shared_output_bitwidth: 5
shared_output_fanin: 1
shared_output_layer: true
seed: 8971561
weight_decay: 0