batch_size: 1024
epochs: 1000
hidden_bitwidth: 3
hidden_fanin: 3
hidden_layers:
- 128
- 128
- 128
- 64
input_bitwidth: 5
input_dropout: 0.001
input_fanin: 2
input_length: 784
learning_rate: 0.001
output_bitwidth: 3
output_fanin: 3
output_length: 10
post_transform_output: true
seed: 2
weight_decay: 0
degree: 3