hidden_layers:
- 64
- 32
- 32
- 32
input_bitwidth: 3
hidden_bitwidth: 3
output_bitwidth: 3
input_fanin: 4
hidden_fanin: 4
output_fanin: 4
weight_decay: 0.001
batch_size: 1024
epochs: 1000
learning_rate: 0.001
seed: 3
checkpoint: null
