activation_bitwidth:
- 3
- 3
- 4
batch_size: 512
width_n: 16
ensemble_hp:
  fixed_sparsity_mask: false
  shared_input_bitwidth: 6
  shared_input_layer: true
  shared_output_bitwidth: 6
  shared_output_fanin: 1
  shared_output_layer: true
ensemble_method: voting
ensemble_size: 2
epochs: 200
hidden_layer:
- 512
- 512
- 64
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 4
- 5
- 3
output_bitwidth: 5
seed: 1
warm_restart_freq: 100
wd: 0