batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 16
epochs: 1000
hidden_bitwidth: 3
hidden_fanin: 4
hidden_layers:
- 64
- 32
- 32
- 32
input_bitwidth: 3
input_fanin: 4
input_length: 16
learning_rate: 0.001
output_bitwidth: 3
output_fanin: 4
output_length: 5
post_transform_output: true
quantize_avg: false
same_input_scale: false
same_output_scale: false
seed: 3
uniform_input_connectivity: true
weight_decay: 0.001
