activation_bitwidth:
- 3
- 4
batch_size: 512
degree: 2
epochs: 200
hidden_layer:
- 64
- 128
input_bitwidth: 5
input_fanin: 2
lr: 0.001
neuron_fanin:
- 3
- 3
output_bitwidth: 4
seed: 0
warm_restart_freq: 100
wd: 0.0001
