activation_bitwidth:
- 2
- 2
- 2
- 6
batch_size: 512
degree: 2
ensemble_method: voting
ensemble_size: 2
epochs: 200
gpu: true
hidden_layer:
- 128
- 256
- 128
- 128
input_bitwidth: 4
input_fanin: 2
lr: 0.001
neuron_fanin:
- 6
- 5
- 4
- 2
output_bitwidth: 6
seed: 3
warm_restart_freq: 100
wd: 0
